"""Report service — orchestrates report creation and retrieval.

Storage is intentionally isolated behind a repository interface so it can be
swapped from in-memory to Supabase without changing the service contract.
All business logic stays here; route handlers remain thin (Part A §6).

Persistence strategy:
  1. Always build the ReportOut object and write it to _STORE (in-memory).
  2. If Supabase is fully configured (URL + SERVICE_KEY), also persist to the
     public.reports table via report_repo, using the authenticated user_id.
  3. On any Supabase error, the in-memory entry is already present so the
     response is unaffected.

Read strategy:
  1. Try Supabase first (get_report / list_reports).
  2. Fall back to _STORE if Supabase is unconfigured or the row is not found.
  This means data written to Supabase is visible even after a process restart,
  while the app degrades gracefully to in-memory when Supabase is unavailable.

T3-3 security notes:
  - create_report() accepts an optional user_id from the authenticated JWT sub.
  - DEMO_USER_ID is used as fallback only when user_id is not provided (local dev
    without auth enabled, or in-memory-only mode).
  - _supabase_enabled() no longer requires DEMO_USER_ID; URL + SERVICE_KEY suffice.
  - get_report_with_owner() returns (ReportOut, owner_user_id) for IDOR checks.

T3-3 AI pipeline notes:
  - create_report_from_image() is the new async function that wires together:
      image validation (T2-2) → AI pipeline (T2-11) → storage upload → DB insert
  - The existing sync create_report() is preserved unchanged for backward
    compatibility with existing tests and the non-image code path.
  - Signed URLs (15-min expiry) are generated by storage_service and attached
    to the ReportOut before returning (Part A §20).
"""
from __future__ import annotations

import logging
import uuid
from datetime import datetime, timezone
from typing import Optional

from config import settings
from schemas.report import (
    AuthorityOut,
    IssueCategory,
    ReportCreate,
    ReportOut,
    ReportStatus,
    CATEGORY_LABELS,
)
from services.authority_service import get_authority_by_id, route_to_authority

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# In-memory demo repository — kept intact as fallback (Part A §6, T3-3)
# ---------------------------------------------------------------------------

_STORE: dict[str, ReportOut] = {}

# Maps report_id → owner user_id for IDOR checks on the in-memory fallback.
_OWNER_STORE: dict[str, str] = {}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _supabase_enabled() -> bool:
    """True when Supabase URL and service key are configured.

    DEMO_USER_ID is no longer required here — T3-3 supplies the authenticated
    user_id at call time.  DEMO_USER_ID is only used as a fallback inside
    create_report() when no authenticated user_id is provided (local dev).
    """
    return bool(
        settings.SUPABASE_URL
        and settings.SUPABASE_SERVICE_KEY
    )


def _authority_dict_to_out(a: Optional[dict]) -> Optional[AuthorityOut]:
    if a is None:
        return None
    return AuthorityOut(
        id=a["id"],
        name=a["name"],
        short_name=a["short_name"],
        contact_email=a["contact_email"],
        phone=a["phone"],
    )


def _row_to_report_out(row: dict) -> Optional[ReportOut]:
    """Convert a public.reports DB row dict into a ReportOut.

    Field mapping (DB → API):
      id                   → report_id
      ai_category          → category
      address_text         → area_text
      ai_confidence        → confidence
      ai_authority_id      → recommended_authority (re-looked-up from JSON)
      image_original_path  → photo_filename
      image_redacted_path  → (stored; signed URL added by _attach_signed_urls)
      image_hash           → image_hash
      ai_raw_response      → description + match_reason + AI fields (JSONB)
      created_at           → created_at
      status               → status TEXT column (migration 007; default 'SUBMITTED')
      rejection_reason     → rejection_reason TEXT column (migration 007; NULL unless REJECTED)
    """
    try:
        category_val = row.get("ai_category") or "other"
        raw = row.get("ai_raw_response") or {}
        description = raw.get("description", "")
        match_reason = raw.get("match_reason")
        confidence = float(row.get("ai_confidence") or 0.0)
        authority_id = row.get("ai_authority_id")
        authority_dict = get_authority_by_id(authority_id) if authority_id else None
        created_at_val = row.get("created_at")
        if isinstance(created_at_val, str):
            from datetime import datetime as _dt
            # Supabase returns ISO strings; parse robustly.
            created_at_val = _dt.fromisoformat(
                created_at_val.replace("Z", "+00:00")
            )

        # Read status from DB row (migration 007).  Fall back to SUBMITTED for
        # rows that pre-date the migration (status column absent or None).
        raw_status = row.get("status") or "SUBMITTED"
        try:
            db_status = ReportStatus(raw_status)
        except ValueError:
            db_status = ReportStatus.submitted

        return ReportOut(
            report_id=str(row["id"]),
            category=IssueCategory(category_val),
            category_label=CATEGORY_LABELS.get(category_val, category_val),
            area_text=row.get("address_text") or "",
            description=description,
            status=db_status,
            recommended_authority=_authority_dict_to_out(authority_dict),
            match_reason=match_reason,
            confidence=min(max(confidence, 0.0), 1.0),
            created_at=created_at_val or datetime.now(timezone.utc),
            photo_filename=row.get("image_original_path"),
            # T3-3: AI pipeline fields stored in ai_raw_response JSONB
            is_duplicate=bool(raw.get("is_duplicate", False)),
            duplicate_report_id=raw.get("duplicate_report_id"),
            image_hash=row.get("image_hash"),
            llm_provider_used=raw.get("llm_provider_used"),
            yolo_class=raw.get("yolo_class"),
            # Signed URLs are NOT stored in DB; they are generated on read.
            # _attach_signed_urls() adds them after row→ReportOut conversion.
            image_original_url=None,
            image_redacted_url=None,
            # Rejection reason from migration 007 column
            rejection_reason=row.get("rejection_reason"),
        )
    except Exception:
        logger.warning("_row_to_report_out: failed to parse DB row.", exc_info=True)
        return None


def _attach_signed_urls(report: ReportOut, original_path: Optional[str], redacted_path: Optional[str]) -> ReportOut:
    """Generate and attach 15-minute signed URLs to a ReportOut (T3-3 §20).

    Uses storage_service to create signed URLs.  If Supabase is unavailable
    or the path is None, the URL fields remain None — callers must handle this.

    Returns the same ReportOut object (mutated in place for simplicity).
    """
    if not _supabase_enabled():
        return report

    try:
        from services import storage_service

        if original_path:
            report.image_original_url = storage_service.get_original_signed_url(original_path)
        if redacted_path:
            report.image_redacted_url = storage_service.get_redacted_signed_url(redacted_path)
    except Exception:
        logger.warning("_attach_signed_urls: failed to generate signed URLs.", exc_info=True)

    return report


# ---------------------------------------------------------------------------
# Public service API
# ---------------------------------------------------------------------------

async def create_report_from_image(
    image_bytes: bytes,
    claimed_mime: str = "",
    lat: Optional[float] = None,
    lng: Optional[float] = None,
    address: str = "",
    user_id: Optional[str] = None,
) -> ReportOut:
    """Create a new report from raw image bytes via the full AI pipeline (T3-3).

    This is the primary T3-3 entry point:
      1. Run cv/pipeline.run_ai_pipeline() — validates image, redacts, hashes,
         detects, scores confidence, routes authority, generates LLM description.
      2. Upload original image to report-originals bucket via storage_service.
      3. Upload redacted image to report-redacted bucket via storage_service.
      4. Insert DB row with all AI results.
      5. Return ReportOut with signed URLs and AI fields.

    Args:
        image_bytes:  Raw uploaded image bytes.
        claimed_mime: Client-supplied Content-Type (advisory; magic bytes authoritative).
        lat:          GPS latitude from browser geolocation (optional).
        lng:          GPS longitude from browser geolocation (optional).
        address:      Human-readable area text / address for LLM prompts.
        user_id:      Authenticated user's JWT sub.

    Returns:
        ReportOut with all AI results and signed image URLs.

    Raises:
        cv.image_validator.ImageValidationError: when image fails T2-2 validation.
    """
    from cv.pipeline import run_ai_pipeline

    # Build location string for the pipeline (Part A §23).
    location = ""
    if lat is not None and lng is not None:
        location = f"{lat},{lng}"

    # Fetch existing image hashes from DB for duplicate detection (T2-7).
    # This is a best-effort query; failure is non-blocking.
    existing_hashes: list = []
    if _supabase_enabled():
        try:
            from db.repositories import report_repo
            rows = report_repo.list_reports()
            if rows:
                existing_hashes = [
                    (r["image_hash"], r["id"])
                    for r in rows
                    if r.get("image_hash")
                ]
        except Exception:
            logger.warning("create_report_from_image: could not fetch existing hashes.", exc_info=True)

    # Run AI pipeline (T2-11) — may raise ImageValidationError.
    ai_result = await run_ai_pipeline(
        image_bytes=image_bytes,
        location=location,
        address=address or location or "Mangaluru",
        claimed_mime=claimed_mime,
        existing_hashes=existing_hashes,
    )

    report_id = str(uuid.uuid4())
    now = datetime.now(timezone.utc)

    # Resolve authority from AI result.
    authority_id = ai_result.authority_id or None
    authority_dict = get_authority_by_id(authority_id) if authority_id else None

    # Upload images to Supabase Storage (T3-3 §20).
    # Failures are non-blocking — paths will be None if storage is unavailable.
    from services import storage_service

    original_path: Optional[str] = None
    redacted_path: Optional[str] = None
    try:
        original_path = storage_service.upload_original(report_id, ai_result.validated_image_bytes)
    except Exception:
        logger.warning("create_report_from_image: original upload failed.", exc_info=True)
    try:
        redacted_path = storage_service.upload_redacted(report_id, ai_result.redacted_image_bytes)
    except Exception:
        logger.warning("create_report_from_image: redacted upload failed.", exc_info=True)

    category = ai_result.category
    category_val = category.value

    report = ReportOut(
        report_id=report_id,
        category=category,
        category_label=CATEGORY_LABELS.get(category_val, category_val),
        area_text=address or location or "Mangaluru",
        description=ai_result.description,
        status=ReportStatus.submitted,
        recommended_authority=_authority_dict_to_out(authority_dict),
        match_reason=ai_result.match_reason,
        confidence=min(max(ai_result.confidence, 0.0), 1.0),
        created_at=now,
        photo_filename=original_path,
        # T3-3: AI pipeline fields.
        is_duplicate=ai_result.is_duplicate,
        duplicate_report_id=ai_result.duplicate_report_id,
        image_hash=ai_result.image_hash or None,
        llm_provider_used=ai_result.llm_provider_used,
        yolo_class=ai_result.yolo_class or None,
        # Signed URLs will be attached below.
        image_original_url=None,
        image_redacted_url=None,
    )

    # Write to in-memory store first — guarantees response even if DB fails.
    _STORE[report_id] = report
    if user_id:
        _OWNER_STORE[report_id] = user_id

    # Persist to Supabase DB.
    if _supabase_enabled():
        try:
            from db.repositories import report_repo

            effective_user_id = user_id
            if not effective_user_id:
                effective_user_id = settings.DEMO_USER_ID
                if effective_user_id:
                    logger.warning(
                        "create_report_from_image: no authenticated user_id; "
                        "falling back to DEMO_USER_ID '%s'.",
                        effective_user_id,
                    )

            if effective_user_id:
                row = {
                    "id": report_id,
                    "user_id": effective_user_id,
                    "ai_category": category_val,
                    "address_text": report.area_text,
                    "ai_confidence": ai_result.confidence,
                    "ai_authority_id": authority_id,
                    "image_original_path": original_path,
                    "image_redacted_path": redacted_path,
                    "image_hash": ai_result.image_hash or None,
                    "ai_raw_response": {
                        "description": ai_result.description,
                        "match_reason": ai_result.match_reason,
                        "is_duplicate": ai_result.is_duplicate,
                        "duplicate_report_id": ai_result.duplicate_report_id,
                        "llm_provider_used": ai_result.llm_provider_used,
                        "yolo_class": ai_result.yolo_class,
                    },
                }
                inserted = report_repo.insert_report(row)
                if inserted:
                    db_report = _row_to_report_out(inserted)
                    if db_report:
                        # Attach paths for signed URL generation.
                        db_report = _attach_signed_urls(
                            db_report,
                            original_path=inserted.get("image_original_path"),
                            redacted_path=inserted.get("image_redacted_path"),
                        )
                        _STORE[report_id] = db_report
                        return db_report
            else:
                logger.debug(
                    "create_report_from_image: no user_id available; skipping Supabase insert."
                )
        except Exception:
            logger.warning(
                "create_report_from_image: Supabase persist failed — using in-memory result.",
                exc_info=True,
            )

    # Attach signed URLs even for the in-memory path (if storage succeeded).
    report = _attach_signed_urls(report, original_path=original_path, redacted_path=redacted_path)
    return report


def create_report(
    payload: ReportCreate,
    photo_filename: Optional[str] = None,
    user_id: Optional[str] = None,
) -> ReportOut:
    """Create a new report using the text-based form path (backward-compatible).

    This path is used when no image file is supplied.  It calls route_to_authority
    directly (no AI pipeline) and stores the user-provided category/description.

    Args:
        payload:        Validated ReportCreate with category, area_text, description.
        photo_filename: Optional filename of the uploaded photo.
        user_id:        Authenticated user's JWT sub.
    """
    # Authority routing always uses the immutable JSON (ADR-001 — unchanged).
    authority, reason, confidence = route_to_authority(
        payload.category.value,
        payload.area_text,
    )

    report_id = str(uuid.uuid4())
    now = datetime.now(timezone.utc)

    report = ReportOut(
        report_id=report_id,
        category=payload.category,
        category_label=CATEGORY_LABELS[payload.category.value],
        area_text=payload.area_text,
        description=payload.description,
        status=ReportStatus.submitted,
        recommended_authority=_authority_dict_to_out(authority),
        match_reason=reason,
        confidence=confidence,
        created_at=now,
        photo_filename=photo_filename,
    )

    # Always write to in-memory store first — guarantees the response is
    # available regardless of Supabase outcome.
    _STORE[report.report_id] = report

    # Track the owner for IDOR checks on the in-memory fallback (T3-3).
    if user_id:
        _OWNER_STORE[report.report_id] = user_id

    # Attempt Supabase persistence when fully configured.
    if _supabase_enabled():
        try:
            from db.repositories import report_repo

            # Always use the authenticated user_id.
            # DEMO_USER_ID fallback is ONLY for local dev without auth enabled.
            effective_user_id = user_id
            if not effective_user_id:
                effective_user_id = settings.DEMO_USER_ID
                if effective_user_id:
                    logger.warning(
                        "create_report: no authenticated user_id supplied; "
                        "falling back to DEMO_USER_ID '%s'. "
                        "If real users are logged in, clear DEMO_USER_ID in .env "
                        "to prevent demo reports appearing in their report lists.",
                        effective_user_id,
                    )

            if not effective_user_id:
                # No user_id and no DEMO_USER_ID — skip Supabase insert since
                # reports.user_id is NOT NULL.
                logger.debug(
                    "create_report: no user_id available; skipping Supabase insert."
                )
                return report

            row = {
                "id": report_id,
                "user_id": effective_user_id,
                "ai_category": payload.category.value,
                "address_text": payload.area_text,
                "ai_confidence": confidence,
                "ai_authority_id": authority["id"] if authority else None,
                "image_original_path": photo_filename,
                "ai_raw_response": {
                    "description": payload.description,
                    "match_reason": reason,
                },
                # created_at left to DB default (NOW())
            }
            inserted = report_repo.insert_report(row)
            if inserted:
                # Use the DB-assigned created_at so reads are consistent.
                db_report = _row_to_report_out(inserted)
                if db_report:
                    _STORE[report.report_id] = db_report
                    return db_report
        except Exception:
            logger.warning(
                "create_report: Supabase insert failed — using in-memory result.",
                exc_info=True,
            )

    return report


def get_report(report_id: str) -> Optional[ReportOut]:
    # Try Supabase first so data survives process restarts.
    if _supabase_enabled():
        try:
            from db.repositories import report_repo

            row = report_repo.get_report_by_id(report_id)
            if row:
                report = _row_to_report_out(row)
                if report:
                    return _attach_signed_urls(
                        report,
                        original_path=row.get("image_original_path"),
                        redacted_path=row.get("image_redacted_path"),
                    )
        except Exception:
            logger.warning(
                "get_report: Supabase query failed — falling back to in-memory.",
                exc_info=True,
            )

    return _STORE.get(report_id)


def get_report_with_owner(report_id: str) -> Optional[tuple[ReportOut, str]]:
    """Return (ReportOut, owner_user_id) for IDOR checks (T3-3).

    Tries Supabase first (which stores the user_id column directly), then
    falls back to the in-memory _STORE + _OWNER_STORE.

    Returns:
        (report, owner_user_id) if found and owner is known.
        None if the report does not exist.
        (report, "") if the report exists but owner is unknown (in-memory
        reports created before T3-3 auth, e.g. legacy in-memory data) —
        callers should treat an empty owner string as unprotected / skip
        IDOR check.
    """
    # Try Supabase first — the DB row includes user_id.
    if _supabase_enabled():
        try:
            from db.repositories import report_repo

            row = report_repo.get_report_by_id(report_id)
            if row:
                report = _row_to_report_out(row)
                if report:
                    report = _attach_signed_urls(
                        report,
                        original_path=row.get("image_original_path"),
                        redacted_path=row.get("image_redacted_path"),
                    )
                    return report, row.get("user_id", "")
        except Exception:
            logger.warning(
                "get_report_with_owner: Supabase query failed — falling back to in-memory.",
                exc_info=True,
            )

    # In-memory fallback.
    report = _STORE.get(report_id)
    if report is None:
        return None
    owner = _OWNER_STORE.get(report_id, "")
    return report, owner


def list_reports() -> list[ReportOut]:
    """Return ALL reports — for admin use only."""
    # Try Supabase first; fall back to in-memory.
    if _supabase_enabled():
        try:
            from db.repositories import report_repo

            rows = report_repo.list_reports()
            if rows is not None:  # empty list is valid (zero reports)
                reports = []
                for r in rows:
                    report = _row_to_report_out(r)
                    if report:
                        report = _attach_signed_urls(
                            report,
                            original_path=r.get("image_original_path"),
                            redacted_path=r.get("image_redacted_path"),
                        )
                        reports.append(report)
                return reports
        except Exception:
            logger.warning(
                "list_reports: Supabase query failed — falling back to in-memory.",
                exc_info=True,
            )

    return sorted(_STORE.values(), key=lambda r: r.created_at, reverse=True)


def list_reports_for_user(user_id: str) -> list[ReportOut]:
    """Return reports submitted by a specific user.

    Used for the public /reports endpoint so citizens only see their own reports.
    Falls back to filtering the in-memory store by owner when Supabase is unavailable.
    """
    if _supabase_enabled():
        try:
            from db.repositories import report_repo

            rows = report_repo.list_reports_by_user(user_id)
            if rows is not None:
                reports = []
                for r in rows:
                    report = _row_to_report_out(r)
                    if report:
                        report = _attach_signed_urls(
                            report,
                            original_path=r.get("image_original_path"),
                            redacted_path=r.get("image_redacted_path"),
                        )
                        reports.append(report)
                return reports
        except Exception:
            logger.warning(
                "list_reports_for_user: Supabase query failed — falling back to in-memory.",
                exc_info=True,
            )

    # In-memory fallback: filter by owner.
    owned = [
        r for r in _STORE.values()
        if _OWNER_STORE.get(r.report_id) == user_id
    ]
    return sorted(owned, key=lambda r: r.created_at, reverse=True)


def admin_update_report_status(
    report_id: str,
    new_status: ReportStatus,
    rejection_reason: Optional[str],
    admin_user_id: str,
) -> ReportOut:
    """Update a report's status as an admin.  Service-layer entry point.

    This function is the ONLY place where status transition rules are validated.
    Route handlers MUST call this function and not perform transition logic
    themselves (Part A §6 — no business logic in routers).

    Transition rules (Part A §24 state machine):
        SUBMITTED    → UNDER_REVIEW | REJECTED | ARCHIVED
        UNDER_REVIEW → RESOLVED     | REJECTED | ARCHIVED
        RESOLVED     → ARCHIVED
        REJECTED     → ARCHIVED
        ARCHIVED     → (terminal — no further transitions)

    Args:
        report_id:        UUID of the report to update.
        new_status:       Target ReportStatus value.
        rejection_reason: Required (non-empty) when new_status is REJECTED;
                          must be None for all other statuses.
        admin_user_id:    JWT sub of the acting admin (for logging).

    Returns:
        Updated ReportOut with the new status and rejection_reason populated.

    Raises:
        HTTPException 404: Report not found.
        HTTPException 422: Invalid status transition.
    """
    from fastapi import HTTPException, status as http_status
    from schemas.report import STATUS_TRANSITIONS

    # 1. Resolve the current report (Supabase → in-memory fallback).
    result = get_report_with_owner(report_id)
    if result is None:
        raise HTTPException(
            status_code=http_status.HTTP_404_NOT_FOUND,
            detail=f"Report '{report_id}' not found.",
        )

    current_report, _owner_id = result
    current_status = current_report.status

    # 2. Validate the transition.
    allowed_next = STATUS_TRANSITIONS.get(current_status, frozenset())
    if new_status not in allowed_next:
        allowed_str = (
            ", ".join(s.value for s in sorted(allowed_next, key=lambda x: x.value))
            if allowed_next
            else "none (terminal state)"
        )
        raise HTTPException(
            status_code=http_status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=(
                f"Invalid status transition: '{current_status.value}' → '{new_status.value}'. "
                f"Allowed from '{current_status.value}': {allowed_str}."
            ),
        )

    # 3. Persist to Supabase if available; update in-memory store regardless.
    db_updated = False
    if _supabase_enabled():
        try:
            from db.repositories import report_repo

            updated_row = report_repo.update_report_status(
                report_id=report_id,
                new_status=new_status.value,
                rejection_reason=rejection_reason,
            )
            if updated_row:
                updated_report = _row_to_report_out(updated_row)
                if updated_report:
                    updated_report = _attach_signed_urls(
                        updated_report,
                        original_path=updated_row.get("image_original_path"),
                        redacted_path=updated_row.get("image_redacted_path"),
                    )
                    _STORE[report_id] = updated_report
                    db_updated = True
                    logger.info(
                        "admin_update_report_status: report=%s %s→%s by admin=%s (Supabase)",
                        report_id,
                        current_status.value,
                        new_status.value,
                        admin_user_id,
                    )
                    return updated_report
        except HTTPException:
            raise  # Re-raise 404/422 without swallowing them
        except Exception:
            logger.warning(
                "admin_update_report_status: Supabase update failed for report=%s — "
                "applying in-memory update only.",
                report_id,
                exc_info=True,
            )

    # 4. In-memory update (used when Supabase is unavailable or returned no row).
    updated_report = current_report.model_copy(
        update={
            "status": new_status,
            "rejection_reason": rejection_reason,
        }
    )
    _STORE[report_id] = updated_report

    if not db_updated:
        logger.info(
            "admin_update_report_status: report=%s %s→%s by admin=%s (in-memory only)",
            report_id,
            current_status.value,
            new_status.value,
            admin_user_id,
        )

    return updated_report


def update_report_fields(
    report_id: str,
    category: Optional[IssueCategory] = None,
    description: Optional[str] = None,
    authority_id: Optional[str] = None,
) -> "ReportOut":
    """Apply citizen corrections from Stage 2 AI review (Priority 3).

    Updates category, description, and/or authority_id in DB + in-memory store.
    Only fields that are not None are updated.

    Owner check is performed by the router before calling this function.

    Args:
        report_id:    UUID of the report to patch.
        category:     Citizen-confirmed/overridden IssueCategory (None = keep AI value).
        description:  Citizen-edited description (None = keep AI value).
        authority_id: Citizen-chosen authority id (None = keep AI value).

    Returns:
        Updated ReportOut.

    Raises:
        HTTPException 404: Report not found.
    """
    from fastapi import HTTPException, status as http_status

    # 1. Load current report.
    result = get_report_with_owner(report_id)
    if result is None:
        raise HTTPException(
            status_code=http_status.HTTP_404_NOT_FOUND,
            detail=f"Report '{report_id}' not found.",
        )

    current_report, _owner_id = result

    # 2. Resolve effective values.
    effective_category = category if category is not None else current_report.category

    if authority_id is not None:
        authority_dict = get_authority_by_id(authority_id)
        new_authority = _authority_dict_to_out(authority_dict)
        new_match_reason = (
            f"Citizen selected: {authority_dict['short_name']}"
            if authority_dict
            else current_report.match_reason
        )
    else:
        new_authority = current_report.recommended_authority
        new_match_reason = current_report.match_reason

    effective_description = (
        description if description is not None else current_report.description
    )

    # 3. Build updated in-memory ReportOut.
    updated_report = ReportOut(
        report_id=current_report.report_id,
        category=effective_category,
        category_label=CATEGORY_LABELS.get(effective_category.value, effective_category.value),
        area_text=current_report.area_text,
        description=effective_description,
        status=current_report.status,
        recommended_authority=new_authority,
        match_reason=new_match_reason,
        confidence=current_report.confidence,
        created_at=current_report.created_at,
        photo_filename=current_report.photo_filename,
        image_original_url=current_report.image_original_url,
        image_redacted_url=current_report.image_redacted_url,
        is_duplicate=current_report.is_duplicate,
        duplicate_report_id=current_report.duplicate_report_id,
        image_hash=current_report.image_hash,
        llm_provider_used=current_report.llm_provider_used,
        yolo_class=current_report.yolo_class,
        rejection_reason=current_report.rejection_reason,
    )

    # 4. Write to in-memory store immediately (guarantees response on DB failure).
    _STORE[report_id] = updated_report

    # 5. Persist to Supabase if available.
    if _supabase_enabled():
        try:
            from db.repositories import report_repo

            db_updates: dict = {}
            if category is not None:
                db_updates["ai_category"] = effective_category.value
            if authority_id is not None:
                db_updates["ai_authority_id"] = authority_id

            # description lives in ai_raw_response JSONB — merge into existing.
            if description is not None or (authority_id is not None and new_match_reason):
                row = report_repo.get_report_by_id(report_id)
                if row:
                    existing_raw = row.get("ai_raw_response") or {}
                    if description is not None:
                        existing_raw["description"] = effective_description
                    if authority_id is not None:
                        existing_raw["match_reason"] = new_match_reason
                    db_updates["ai_raw_response"] = existing_raw

            if db_updates:
                updated_row = report_repo.update_report_fields(report_id, db_updates)
                if updated_row:
                    db_report = _row_to_report_out(updated_row)
                    if db_report:
                        db_report = _attach_signed_urls(
                            db_report,
                            original_path=updated_row.get("image_original_path"),
                            redacted_path=updated_row.get("image_redacted_path"),
                        )
                        _STORE[report_id] = db_report
                        return db_report
        except Exception:
            logger.warning(
                "update_report_fields: Supabase update failed — using in-memory result.",
                exc_info=True,
            )

    return updated_report
