"""Pydantic schemas for report endpoints — Part A §7, §18."""
from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field, field_validator, model_validator


# ---------------------------------------------------------------------------
# Enums — mirror Part A §7 issue_category and complaint_status
# ---------------------------------------------------------------------------

class IssueCategory(str, Enum):
    pothole = "pothole"
    waterlogging = "waterlogging"
    broken_streetlight = "broken_streetlight"
    garbage_overflow = "garbage_overflow"
    open_drain = "open_drain"
    illegal_construction = "illegal_construction"
    water_supply = "water_supply"
    sewage = "sewage"
    road_damage = "road_damage"
    other = "other"


CATEGORY_LABELS: dict[str, str] = {
    "pothole": "Pothole",
    "waterlogging": "Waterlogging",
    "broken_streetlight": "Broken Streetlight",
    "garbage_overflow": "Garbage Overflow",
    "open_drain": "Open Drain",
    "illegal_construction": "Illegal Construction",
    "water_supply": "Water Supply",
    "sewage": "Sewage",
    "road_damage": "Road Damage",
    "other": "Other",
}


class ReportStatus(str, Enum):
    submitted = "SUBMITTED"
    under_review = "UNDER_REVIEW"
    resolved = "RESOLVED"
    rejected = "REJECTED"
    archived = "ARCHIVED"


# ---------------------------------------------------------------------------
# Evidence verification enums (evidence-verification architecture)
# ---------------------------------------------------------------------------

class DecisionState(str, Enum):
    """Canonical decision state assigned by the evidence decision engine."""
    invalid_image           = "invalid_image"
    insufficient_evidence   = "insufficient_evidence"
    duplicate_active_report = "duplicate_active_report"
    possible_reopened_issue = "possible_reopened_issue"
    valid_civic_report      = "valid_civic_report"
    needs_admin_review      = "needs_admin_review"


class AdminPriority(str, Enum):
    """Deterministic triage classification for the admin dashboard."""
    CRITICAL      = "CRITICAL"
    HIGH          = "HIGH"
    MEDIUM        = "MEDIUM"
    LOW           = "LOW"
    REOPEN_REVIEW = "REOPEN_REVIEW"
    DUPLICATE     = "DUPLICATE"
    INSUFFICIENT  = "INSUFFICIENT"


# ---------------------------------------------------------------------------
# Authority sub-schema
# ---------------------------------------------------------------------------

class AuthorityOut(BaseModel):
    id: str
    name: str
    short_name: str
    contact_email: str
    phone: str


# ---------------------------------------------------------------------------
# Request schema
# ---------------------------------------------------------------------------

class ReportCreate(BaseModel):
    category: IssueCategory
    area_text: str = Field(..., min_length=2, max_length=500)
    description: str = Field(..., min_length=10, max_length=2000)
    # GPS accuracy from browser geolocation API (optional, metres)
    gps_accuracy: Optional[float] = Field(None, ge=0.0)

    @field_validator("area_text", "description", mode="before")
    @classmethod
    def strip_whitespace(cls, v: str) -> str:
        return v.strip()


# ---------------------------------------------------------------------------
# Response schema
# ---------------------------------------------------------------------------

class ReportOut(BaseModel):
    report_id: str
    category: IssueCategory
    category_label: str
    area_text: str
    description: str
    status: ReportStatus
    recommended_authority: Optional[AuthorityOut] = None
    match_reason: Optional[str] = None
    confidence: float = Field(ge=0.0, le=1.0, default=0.0)
    created_at: datetime
    photo_filename: Optional[str] = None
    # T3-3: Storage signed URLs (15-min expiry, generated by storage_service)
    image_original_url: Optional[str] = None
    image_redacted_url: Optional[str] = None
    # T3-3: AI pipeline fields from cv/pipeline.py AIResult
    is_duplicate: bool = False
    duplicate_report_id: Optional[str] = None
    image_hash: Optional[str] = None
    llm_provider_used: Optional[str] = None
    yolo_class: Optional[str] = None
    # Admin status management — rejection reason visible to citizen (if rejected)
    rejection_reason: Optional[str] = None
    # Evidence verification architecture fields
    decision_state: Optional[str] = None
    evidence_score: Optional[float] = Field(None, ge=0.0, le=1.0)
    admin_priority: Optional[str] = None
    severity: Optional[str] = None
    is_reopened: bool = False
    linked_report_id: Optional[str] = None
    image_reuse_flag: bool = False
    # citizen_message: shown to citizen instead of raw scores
    citizen_message: Optional[str] = None
    # evidence_breakdown: admin-only (never returned to citizens in public endpoints)
    # Returned ONLY by GET /api/v1/admin/reports/{id}/evidence
    evidence_breakdown: Optional[Any] = None


class ReportListOut(BaseModel):
    reports: list[ReportOut]
    total: int


# ---------------------------------------------------------------------------
# Admin status update request schema
# ---------------------------------------------------------------------------

# Allowed target statuses an admin may set — mirrors Part A §24 state machine.
# DRAFT is not a valid target (reports start as SUBMITTED from the API).
ADMIN_ALLOWED_STATUSES: frozenset[ReportStatus] = frozenset({
    ReportStatus.under_review,
    ReportStatus.resolved,
    ReportStatus.rejected,
    ReportStatus.archived,
})

# Valid transitions: {current_status: set_of_allowed_next_statuses}
# Part A §24 state machine — only admin-driven transitions are listed here.
# SUBMITTED → UNDER_REVIEW or REJECTED (admin may also archive submitted reports)
# UNDER_REVIEW → RESOLVED or REJECTED or ARCHIVED
# RESOLVED → ARCHIVED
# REJECTED → ARCHIVED
# ARCHIVED → (terminal, no further transitions)
STATUS_TRANSITIONS: dict[ReportStatus, frozenset[ReportStatus]] = {
    ReportStatus.submitted: frozenset({
        ReportStatus.under_review,
        ReportStatus.rejected,
        ReportStatus.archived,
    }),
    ReportStatus.under_review: frozenset({
        ReportStatus.resolved,
        ReportStatus.rejected,
        ReportStatus.archived,
    }),
    ReportStatus.resolved: frozenset({
        ReportStatus.archived,
    }),
    ReportStatus.rejected: frozenset({
        ReportStatus.archived,
    }),
    ReportStatus.archived: frozenset(),  # terminal
}

REJECTION_REASON_MAX_LENGTH = 500


class AdminStatusUpdate(BaseModel):
    """Request body for PATCH /api/v1/admin/reports/{id}/status.

    Rules:
      - new_status must be one of ADMIN_ALLOWED_STATUSES.
      - rejection_reason is REQUIRED when new_status is REJECTED.
      - rejection_reason is NOT allowed for non-REJECTED statuses
        (keeps the data model clean; prevents confusion).
      - rejection_reason is validated and length-limited.
    """

    new_status: ReportStatus = Field(
        ...,
        description=(
            "Target report status. Must be one of: "
            + ", ".join(s.value for s in sorted(ADMIN_ALLOWED_STATUSES, key=lambda x: x.value))
        ),
    )
    rejection_reason: Optional[str] = Field(
        None,
        max_length=REJECTION_REASON_MAX_LENGTH,
        description=(
            "Short reason for rejection. Required when new_status is REJECTED. "
            "Structured examples: 'Duplicate report', 'Invalid / unclear image', "
            "'Not a civic issue', 'Wrong / insufficient location', "
            "'Insufficient information', 'Other'."
        ),
    )

    @field_validator("new_status")
    @classmethod
    def validate_allowed_status(cls, v: ReportStatus) -> ReportStatus:
        if v not in ADMIN_ALLOWED_STATUSES:
            raise ValueError(
                f"Status '{v.value}' is not an allowed admin-set status. "
                f"Allowed: {', '.join(s.value for s in sorted(ADMIN_ALLOWED_STATUSES, key=lambda x: x.value))}"
            )
        return v

    @field_validator("rejection_reason", mode="before")
    @classmethod
    def strip_rejection_reason(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None
        stripped = str(v).strip()
        return stripped if stripped else None

    @model_validator(mode="after")
    def validate_rejection_reason_required(self) -> "AdminStatusUpdate":
        if self.new_status == ReportStatus.rejected and not self.rejection_reason:
            raise ValueError(
                "rejection_reason is required when new_status is REJECTED."
            )
        if self.new_status != ReportStatus.rejected and self.rejection_reason is not None:
            raise ValueError(
                "rejection_reason must only be provided when new_status is REJECTED."
            )
        return self


# ---------------------------------------------------------------------------
# Citizen report patch schema (Priority 3 — AI-first review stage)
# ---------------------------------------------------------------------------

class ReportPatch(BaseModel):
    """Request body for PATCH /api/v1/reports/{id}.

    Called in Stage 2 when the citizen confirms (or edits) the AI result.
    All fields are optional — only supplied fields are updated.

    Rules:
      - description must be at least 10 chars if supplied (enforced in router
        after sanitization).
      - category must be a valid IssueCategory if supplied.
      - authority_id must be a valid authority id string if supplied.
      - Caller must be the report owner (IDOR check in router).
    """

    category: Optional[IssueCategory] = Field(None)
    description: Optional[str] = Field(None, min_length=10, max_length=2000)
    authority_id: Optional[str] = Field(None, max_length=64)

    @field_validator("description", mode="before")
    @classmethod
    def strip_description(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None
        stripped = str(v).strip()
        return stripped if stripped else None

    @field_validator("authority_id", mode="before")
    @classmethod
    def strip_authority_id(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None
        stripped = str(v).strip()
        return stripped if stripped else None
